language : cpp
matrix:
  include:
    - os : linux
      dist: xenial
      addons:
        apt:
          sources:
            ubuntu-toolchain-r-test
          packages:
            g++-7
      env:
        MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
install:
  - sudo apt-get install python3 python3-pip python python-pip
  - sudo pip3 install
  - sudo pip3 install pytest pexpect
  - sudo pip install conan
  - conan profile new default --detect && conan profile update 'settings.compiler.libcxx=libstdc++11' default
  - conan install .
  - source activate.sh

before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - ./testBin/libgsc_CatchTests
  - py.test
